Multiple RFEs
UrbanCode/IBM-Integration-Bus-UCD pull request #26
Opened 2018-06-11 21:42 UTC by jrbarto

* PLUGINS-44 Added step to delete an execution group.
* PLUGINS-42 Added a parameter to the deploy step to specify a full/incremental deployment.

2018-06-14 13:36 UTC, nhmathis requested changes

2018-06-14 13:36 UTC, nhmathis commented on src/main/zip/delete_exe_group.groovy
> +    boolean deleteLibs = Boolean.valueOf(props['deleteLibs'])
You don't use this `deleteLibs` parameter.

2018-06-14 13:36 UTC, nhmathis commented on src/main/zip/plugin.xml
> +        <value label="Parameter">${p?:iib.deployType}</value>
The label should be `${p?:iib.deployType}` too. The user will need to know what parameter to set.

2018-06-14 13:36 UTC, nhmathis commented on src/main/zip/plugin.xml
> +        <value label="Parameter">${p?:iib.deployType}</value>
Why is the default the parameter? Shouldn't it be full? That's what we've had to date, right?

2018-06-14 13:36 UTC, nhmathis commented on src/main/zip/deploy.groovy
> +String deployType = props['deployType']
`String deployType = props['deployType']?.trim()`

For safety since you are making it "equal" rather than "contain" `incremental`

2018-06-14 14:08 UTC, jrbarto commented
Made the suggested changes.

2018-06-25 17:28 UTC, nhmathis approved these changes

2018-07-23 15:24 UTC, merged